options:
  vgpu-device-mappings:
    type: string
    default:
    description: |
      YAML-formatted dict (or JSON-formatted, since JSON is valid YAML) where
      keys are vGPU types and values are physical addresses, e.g.
      .
      {'nvidia-35': ['0000:84:00.0', '0000:85:00.0'], 'nvidia-36': ['0000:86:00.0']}
      .
      See
      https://docs.openstack.org/nova/ussuri/admin/virtual-gpu.html#enable-gpu-types-compute
      and
      https://docs.openstack.org/nova/ussuri/admin/virtual-gpu.html#how-to-discover-a-gpu-type
      for more details.
  force-install-nvidia-vgpu:
    type: boolean
    default: false
    description: |
      FOR TESTING ONLY. If true, the NVIDIA vGPU software will be installed and
      set up on all units regardless of the presence of NVIDIA GPU hardware. If
      false, the software will be installed and set up only on units where that
      hardware is present.
